#!/usr/bin/env python3
"""Import tour photos: assign each to a show, resize, and emit src/data/photos.ts.

Assignment rules, in order:
  1. GPS within 25 mi of a venue on the target leg -> that venue's show
     (filename twins like `X.jpg` / `X-1.jpg` share the GPS of their sibling)
  2. Otherwise nearest show by date; ties go to the LATER show (touring moves
     forward — off-day files belong to the journey toward the next city)

Reads GPS via Spotlight (mdls), so originals never need exiftool. Originals
are not copied — only resized derivatives land in public/photos/{showId}/.

Usage: python3 scripts/import-photos.py "<source folder>" <legId>
"""

import math
import os
import re
import subprocess
import sys
from datetime import date

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GPS_VENUE_MILES = 25
THUMB_PX = 400
LIGHTBOX_PX = 1600


def read(path):
    with open(path) as f:
        return f.read()


def mdls(path, attr):
    out = subprocess.run(
        ["mdls", "-raw", "-name", attr, path], capture_output=True, text=True
    ).stdout.strip()
    return None if out in ("(null)", "") else out


def is_vsco(path):
    with open(path, "rb") as f:
        return b"VSCO" in f.read(262144)


def miles(a, b, c, d):
    h = (
        math.sin(math.radians(c - a) / 2) ** 2
        + math.cos(math.radians(a)) * math.cos(math.radians(c)) * math.sin(math.radians(d - b) / 2) ** 2
    )
    return 2 * 3958.8 * math.asin(math.sqrt(h))


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src_dir, leg_id = sys.argv[1], sys.argv[2]

    venues = {}
    for m in re.finditer(
        r"id: '([^']+)',.*?lat: ([-\d.]+),\s*lng: ([-\d.]+)",
        read(f"{REPO}/src/data/venues.ts"),
        re.S,
    ):
        venues[m.group(1)] = (float(m.group(2)), float(m.group(3)))

    shows = []  # (showId, venueId, date)
    for m in re.finditer(
        r"\{ id: '([^']+)', legId: '%s', venueId: '([^']+)', date: '([^']+)'" % re.escape(leg_id),
        read(f"{REPO}/src/data/shows.ts"),
    ):
        shows.append((m.group(1), m.group(2), date.fromisoformat(m.group(3))))
    if not shows:
        sys.exit(f"no shows found for leg {leg_id}")

    name_re = re.compile(r"^(\d{4})-(\d{2})-(\d{2}) (\d{2})\.(\d{2})\.(\d{2})(-\d+)?\.(jpe?g|png)$", re.I)
    entries = []
    skipped = []
    for fname in sorted(os.listdir(src_dir)):
        m = name_re.match(fname)
        if not m:
            skipped.append(fname)
            continue
        y, mo, d, hh, mm, ss, suffix, _ext = m.groups()
        path = os.path.join(src_dir, fname)
        lat = mdls(path, "kMDItemLatitude")
        lng = mdls(path, "kMDItemLongitude")
        entries.append({
            "fname": fname,
            "path": path,
            "stem": f"{y}{mo}{d}-{hh}{mm}{ss}" + (suffix or ""),
            "twin_key": f"{y}-{mo}-{d} {hh}.{mm}.{ss}",
            "date": date(int(y), int(mo), int(d)),
            "taken": f"{y}-{mo}-{d}T{hh}:{mm}:{ss}",
            "lat": float(lat) if lat else None,
            "lng": float(lng) if lng else None,
            "camera": mdls(path, "kMDItemAcquisitionModel"),
            "vsco": is_vsco(path),
        })

    # filename twins (original + edit) share GPS
    gps_by_twin = {e["twin_key"]: (e["lat"], e["lng"]) for e in entries if e["lat"] is not None}

    for e in entries:
        lat, lng = e["lat"], e["lng"]
        borrowed = None
        if lat is None and e["twin_key"] in gps_by_twin:
            borrowed = gps_by_twin[e["twin_key"]]
        glat, glng = (lat, lng) if lat is not None else (borrowed or (None, None))

        assigned = None
        if glat is not None:
            near = min(shows, key=lambda s: miles(glat, glng, *venues[s[1]]))
            if miles(glat, glng, *venues[near[1]]) <= GPS_VENUE_MILES:
                assigned = near
        if assigned is None:
            best = min(abs((s[2] - e["date"]).days) for s in shows)
            assigned = [s for s in shows if abs((s[2] - e["date"]).days) == best][-1]
        e["showId"] = assigned[0]

    # resize derivatives
    for e in entries:
        out_dir = f"{REPO}/public/photos/{e['showId']}"
        os.makedirs(out_dir, exist_ok=True)
        for size, tag in ((THUMB_PX, "t"), (LIGHTBOX_PX, "l")):
            out = f"{out_dir}/{e['stem']}_{tag}.jpg"
            if not os.path.exists(out):
                subprocess.run(
                    ["sips", "-Z", str(size), "-s", "format", "jpeg",
                     "-s", "formatOptions", "75", e["path"], "--out", out],
                    capture_output=True, check=True,
                )

    entries.sort(key=lambda e: e["taken"])
    lines = [
        "import type { Photo } from '../types';",
        "",
        "// Generated by scripts/import-photos.py — safe to hand-edit assignments.",
        "export const photos: Photo[] = [",
    ]
    for e in entries:
        parts = [
            f"id: '{e['stem']}'",
            f"showId: '{e['showId']}'",
            f"takenAt: '{e['taken']}'",
        ]
        if e["lat"] is not None:
            parts.append(f"lat: {e['lat']:.6f}")
            parts.append(f"lng: {e['lng']:.6f}")
        if e["camera"]:
            parts.append(f"camera: '{e['camera']}'")
        if e["vsco"]:
            parts.append("vsco: true")
        lines.append("  { " + ", ".join(parts) + " },")
    lines += ["];", ""]
    with open(f"{REPO}/src/data/photos.ts", "w") as f:
        f.write("\n".join(lines))

    with_gps = sum(1 for e in entries if e["lat"] is not None)
    print(f"imported {len(entries)} photos ({with_gps} with GPS) across "
          f"{len({e['showId'] for e in entries})} shows")
    for s in shows:
        n = sum(1 for e in entries if e["showId"] == s[0])
        if n:
            print(f"  {s[2]}  {s[0]:28s} {n}")
    if skipped:
        print(f"skipped {len(skipped)}: " + ", ".join(skipped))


if __name__ == "__main__":
    main()
